# Generated by Django 5.2.17 on 2026-09-23 09:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Savdo nomi')),
                ('dosage', models.CharField(max_length=80, verbose_name='Dozasi')),
                ('form', models.CharField(max_length=80, verbose_name='Dori shakli')),
                ('active_ingredients', models.TextField(blank=True, verbose_name='Tarkibi / faol moddalar')),
                ('indications', models.TextField(blank=True, verbose_name='Rasmiy yo‘riqnomaga ko‘ra qo‘llanishi')),
                ('source', models.TextField(blank=True, verbose_name='Manba (yo‘riqnoma nomi, versiyasi yoki havola)')),
                ('reviewed_on', models.DateField(blank=True, null=True, verbose_name='Tibbiy ma’lumot tekshirilgan sana')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narxi (so‘m)')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Xayoliy namuna')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('search_text', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
                'ordering': ['name', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120, verbose_name='Bo‘lim')),
                ('shelf', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Polka')),
                ('row', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Qator')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Mavjud soni')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalog.medicine')),
            ],
            options={
                'verbose_name': 'Joylashuv',
                'verbose_name_plural': 'Joylashuvlar',
                'ordering': ['department', 'shelf', 'row'],
                'constraints': [models.UniqueConstraint(fields=('medicine', 'department', 'shelf', 'row'), name='unique_placement'), models.CheckConstraint(condition=models.Q(('row__gte', 1), ('shelf__gte', 1)), name='positive_coordinates')],
            },
        ),
    ]
