# Generated by Django 5.2.17 on 2026-09-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_preserve_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='placements', to='catalog.batch'),
        ),
    ]
