# Generated by Django 5.2.17 on 2026-09-23 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_placement_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField(verbose_name='Rejalashtirilgan boshlanish')),
                ('planned_end', models.DateTimeField(verbose_name='Rejalashtirilgan tugash')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Aptekachi')),
            ],
            options={
                'verbose_name': 'Ish jadvali',
                'verbose_name_plural': 'Ish jadvallari',
                'ordering': ['-planned_start', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift', to='catalog.shiftschedule'),
        ),
        migrations.AddConstraint(
            model_name='shiftschedule',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end__gt', models.F('planned_start'))), name='schedule_positive_duration'),
        ),
    ]
