# Generated by Django 5.2.17 on 2026-09-23 15:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_shiftschedule_shift_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Partiya', 'verbose_name_plural': 'Partiyalar'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-started_at', '-pk'], 'verbose_name': 'Smena', 'verbose_name_plural': 'Smenalar'},
        ),
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Polkalar orasida ko‘chirish', 'verbose_name_plural': 'Polkalar orasida ko‘chirishlar'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.medicine', verbose_name='Dori'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='catalog.medicine', verbose_name='Dori'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Bekor qilgan xodim'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana va vaqt'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dosage',
            field=models.CharField(max_length=80, verbose_name='Dozasi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='form',
            field=models.CharField(max_length=80, verbose_name='Dori shakli'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Dori nomi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='package_size',
            field=models.CharField(max_length=120, verbose_name='Qadoq hajmi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.placement', verbose_name='Partiya va joylashuv'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Pachkalar soni'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.shift', verbose_name='Smena'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bir pachka narxi'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift', to='catalog.shiftschedule', verbose_name='Ish jadvali'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana va vaqt'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='catalog.placement', verbose_name='Yangi joy'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_label',
            field=models.CharField(max_length=200, verbose_name='Yangi joy'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Pachkalar soni'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='catalog.placement', verbose_name='Oldingi joy'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_label',
            field=models.CharField(max_length=200, verbose_name='Oldingi joy'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Xodim'),
        ),
    ]
