# Generated by Django 5.2.17 on 2026-09-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_batch_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='placements', to='catalog.batch', verbose_name='Partiya'),
        ),
    ]
